spring:
  application:
    name: springboot-influxdb
server:
  port: 8080
management:
  metrics:
    export:
      influx:
        enabled: true
        db: pkslow
        uri: http://localhost:8086
        user-name:
        password:
        connect-timeout: 1s
        read-timeout: 10s
        auto-create-db: true
        step: 1m
        num-threads: 2
        consistency: one
        compressed: true
        batch-size: 1000