server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
      - id: pkslow
        uri: https://www.pkslow.com
        predicates:
        - Path=/pkslow/**
        filters:
        - RewritePath=/pkslow(?<segment>.*), /$\{segment}
management:
  endpoints:
    web:
      exposure:
        include: "*"
