apiVersion: v1
kind: Pod
metadata:
  name: pkslow-env-env-from
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
        - configMapRef:
            name: pkslow-yaml
  restartPolicy: Never