apiVersion: v1
kind: Pod
metadata:
  name: pkslow-mount-subpath
spec:
  volumes:
    - name: config-volume
      configMap:
        name: pkslow-yaml
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "sleep 1000000" ]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: config-volume
          mountPath: /data/config/dev.yaml
          subPath: application.yaml
        - name: config-volume
          mountPath: /data/config/uat.yaml
          subPath: application-uat.yaml
  restartPolicy: Never